# RESPUESTAS
## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.
### Answer:
H is a hermitian matrix and its eigenvalues are: $$ Eigenvalues= \begin{bmatrix} 4.44948974 & -6.70989255e-17i \\-0.44948974 & +1.15877743e-17i \end{bmatrix} $$

In [19]:
import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[3+0j, 2+1j], [2-1j, 1+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)
import numpy as np

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(hermitian_matrix)

print("Eigenvalues:", eigenvalues)

is_hermitian, hermitian_matrix

Eigenvalues: [ 4.44948974-6.70989255e-17j -0.44948974+1.15877743e-17j]


(True,
 array([[3.+0.j, 2.+1.j],
        [2.-1.j, 1.+0.j]]))

## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.
### Answer:
U is a unitary matrix and $$ UU^\dagger =0i $$

In [20]:

# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2)+0j, 1/np.sqrt(2)*1j], [1/np.sqrt(2)*1j, 1/np.sqrt(2)+0j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))



adjunct_unitary_matrix = unitary_matrix.T.conj()
complex_internal_product_matrix = np.trace(np.dot(np.conjugate(unitary_matrix).T, adjunct_unitary_matrix))

is_unitary, unitary_matrix,complex_internal_product_matrix

(True,
 array([[0.70710678+0.j        , 0.        +0.70710678j],
        [0.        +0.70710678j, 0.70710678+0.j        ]]),
 0j)

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.
### Answer
The tensor product$$ \mathbf{v} \otimes \mathbf{w}  =  \begin{bmatrix} 3-i & 3+3i \\ -5i & 6-3i \end{bmatrix}$$

In [16]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+1j, 2-1j])
v2 = np.array([1-2j, 3])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v

array([3.-1.j, 3.+3.j, 0.-5.j, 6.-3.j])

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.
### Answer
The tensor product$$ \mathbf{v} \otimes \mathbf{w}  =  \begin{bmatrix} 0 & 0 & i & 0 \\ 0 & 0 & 0 & -i \\ i & 0 & 0 & 0 \\ 0 & -i & 0 & 0\end{bmatrix}$$

In [21]:

# Define two complex matrices for the tensor product
M1 = np.array([[0, 1], [1, 0]])
M2 = np.array([[1j, 0], [0, -1j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


array([[0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.-0.j, 0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j, 0.+0.j, 0.-0.j]])

## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)

### Answer 
$$ M =  \frac{1}{\sqrt{2}}\begin{bmatrix} 0 \\ 0 \\ -1 \\ 1 \end{bmatrix}$$

In [11]:

array_a= np.array([[1/np.sqrt(2), (1/np.sqrt(2))], [(1/np.sqrt(2)), -1/np.sqrt(2)]])
s1 = np.array([[1],[0]]) 
s2 = np.array([[0],[1]])
array_uf = np.array([[0,1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1]])
array_b = np.array([[1,0], [0,1]])

A=np.kron (array_a,array_a) 
B=np.kron (s1, s2) 
C = np.dot (A,B) 
D = np.kron (array_a, array_b) 
E= np.dot (array_uf, C) 
print (np.dot (D, E)) 


[[ 0.        ]
 [ 0.        ]
 [-0.70710678]
 [ 0.70710678]]
